using Entities;
using Microsoft.EntityFrameworkCore;
using Repositories;
using RepositoryContracts;
using ServiceContracts;
using Services;
using CRUD.Middleware;

var builder = WebApplication.CreateBuilder(args);

//Enables only Console logging (Terminal) and removes Debug logging in Visual Studio
builder.Host.ConfigureLogging(loggingProviders =>
{
    loggingProviders.ClearProviders();
    loggingProviders.AddConsole();
    loggingProviders.AddDebug();
    loggingProviders.AddEventLog();
});

builder.Services.AddControllersWithViews();

//Add services to IoC container

//Add Repositories to IoC container
builder.Services.AddScoped<ICountriesRepository, CountriesRepository>();
builder.Services.AddScoped<IPersonsRepository, PersonsRepository>();

//Since we are using In-Memory Collection so to persist it we are creating a Singleton service
//builder.Services.AddSingleton<ICountriesService, CountriesService>();
//builder.Services.AddSingleton<IPersonsService, PersonsService>();

//Now we are using a SqlServer DB so use Scoped service
builder.Services.AddScoped<ICountriesService, CountriesService>();
builder.Services.AddScoped<IPersonsService, PersonsService>();

//Add DbContext as a service

//These options params will be supplied to the DbContext constructor class via child constructor
//This is by default will be a Scoped Service
builder.Services.AddDbContext<ApplicationDbContext>(options =>
    options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")));

var app = builder.Build();

//enable httplogging
//http logs are generated by asp.net core so we need to enable them in appsettings.development.json
app.UseHttpLogging();

if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}
else
{
    app.UseExceptionHandler("/Error");
    app.UseExceptionHandlingMiddleware();
}

app.UseStaticFiles();
app.MapControllers();

app.Run();
